project_id = "ccibslznriatjflaknso"

[functions.xtream-api]
verify_jwt = false

[functions.stream-control]
verify_jwt = false

[functions.secure-server-management]
verify_jwt = true

[functions.playlist-generator]
verify_jwt = false

[functions.player-api]
verify_jwt = false

[functions.get]
verify_jwt = false